#!/usr/bin/env python
###############################################################################
#
# Copyright (c) 2009 Novell, Inc.
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public License 
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
#
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com
#
###############################################################################

################################################################################
#
# !!!!! IMPORTANT !!!!! IMPORTANT !!!!
# 
# this script is called from the post install script of the rpm
# so no matter what happens it must alway exit with status 0 !!
#
################################################################################
try:
    import sys
    import os
# Not elegant code but it allows us to build one RPM For all distributions
# and platforms. This is the only platform-specific thing we need to do.
    if sys.getdefaultencoding() != 'utf-8':
        lib_dir = filter(lambda p: p[-3:]==sys.version[:3], sys.path)[0]
        sitecust_filename = os.path.join(lib_dir, 'sitecustomize.py')
        sitecust = open(sitecust_filename, 'a')
        sitecust.write("\n\n")
        sitecust.write("### START CHANGES BY stasis ###\n")
        sitecust.write("import sys\n")
        sitecust.write("sys.setdefaultencoding('utf-8')\n")
        sitecust.write("### END CHANGES BY stasis ###\n")
        sitecust.close()
except:
    try:
        sitecust.close()
    except:
        pass

